name: Deploy Three-Tier App to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and Test
      run: |
        echo "Building and testing application..."
        cd frontend && npm install
        cd ../backend && npm install

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /app
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          echo "Deployment completed!"
